"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

MAX_NUMBER = 4000000
sequence = [1, 2]

def fibonacci(max_number, start_sequence):
    sequence = start_sequence
    while sequence[-1] < max_number:
        next_number = (sequence[-1] + sequence[-2])
        sequence.append(next_number)
        
    sequence.pop() #Remove last number, which exceeds max_number
    return sequence
    
    
fibonacci = fibonacci(MAX_NUMBER, sequence)
fibonacci_even = [i for i in fibonacci if i % 2 == 0]
print(fibonacci_even)
print(sum(fibonacci_even))


        
    
    
